### ISSUE TITLE
HTTPS化

### ISSUE THREAD

**Issue by Milly** [VOCALENDAR/vocalendar-web#2]
## 現状

* SSL は有効
* Let's Encrypt による証明書
* [スマホ向けサイト](https://vocalendar.jp/sp/)がHTTPSで動作しない
  * httpからリソースを読み込んでいるため

## 修正方法

* リソースの読込先をスキーマに合わせる

**Comment by sugi** [comment]
スマホ向けの /sp/ は廃止された (slack参照) ので、これは気にしなくて良くなった。
