### ISSUE TITLE
常時SSL化

### ISSUE THREAD

**Issue by Milly** [VOCALENDAR/vocalendar-web#4]
#2 が完了後、問題なければ常時SSL化(HTTPS優先)に移行する。

* 全てのページをhttpsに301リダイレクトする
  * [mod_rewrite](https://httpd.apache.org/docs/current/ja/mod/mod_rewrite.html)
* HSTSを定義する
  * [mod_headers](https://httpd.apache.org/docs/current/ja/mod/mod_headers.html)
* Googleにhttpsをインデックスさせる
* アプリからhttpsを参照しているかチェックする

参考: [Webサイト利用者やGoogleを適切にHTTPSに誘導する方法](https://zenlogic.jp/aossl/operation/unify-access/)

**Comment by sugi** [comment]
ブラウザはそれでOK なんですが、先に（と言うか並行して） Android/iPhone アプリのコードを確認した方が良いです。

エンドポイントが 30[12] を返した場合、 API を使っているクライアントは追いかけない可能性も高いです。

**Comment by nat0468** [comment]
反応遅くなりましたが、Androidアプリのコード確認しました。
Androidアプリからは下記のURLを参照しているので、httpからhttpsに変更必要ですね。

- Core API (http://vocalendar.jp/core/)
- ヘルプ (http://vocalendar.jp/apps/android/help/)
- お知らせ機能用 (http://vocalendar.jp/announcement/)
https://docs.google.com/document/d/1AMAAqv5809UxUa7MS5-bB3GD3jdaFfuDNJAB7vJUNgA/edit?usp=sharing

上記の変更を含めて、今月中にAndroidアプリをマイナーアップデートしようと準備中です。
マイナーアップデート版をリリース後、ユーザーが乗り換えるための期間(数週間くらい？)を置けば、常時SSL化へ移行しても問題なくなるかと。(iOS版の方は、やじうまさん次第だけど)

**Comment by yajiuma** [comment]
iOSアプリは最初のリリースverからhttps参照してるので問題ないです！

**Comment by sugi** [comment]
リダイレクトと HSTS ヘッダの追加 done
